"""empty message

Revision ID: 51a6166c3d04
Revises: 377fc7f58468
Create Date: 2024-11-09 00:28:15.446860

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '51a6166c3d04'
down_revision = '377fc7f58468'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('carbon_emissions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('year', sa.Integer(), nullable=False),
    sa.Column('emissions', sa.Float(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('device_type',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('device_usage',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('device_type_id', sa.Integer(), nullable=True),
    sa.Column('energy_used', sa.Float(), nullable=False),
    sa.ForeignKeyConstraint(['device_type_id'], ['device_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('energy_usage', schema=None) as batch_op:
        batch_op.alter_column('device_id',
               existing_type=mysql.VARCHAR(length=50),
               type_=sa.Integer(),
               nullable=True)
        batch_op.create_foreign_key(None, 'device_usage', ['device_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('energy_usage', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.alter_column('device_id',
               existing_type=sa.Integer(),
               type_=mysql.VARCHAR(length=50),
               nullable=False)

    op.drop_table('device_usage')
    op.drop_table('device_type')
    op.drop_table('carbon_emissions')
    # ### end Alembic commands ###
